### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by yoksanherlie**
Don't know why there are still the old commits?

### CODE REVIEW

**Comment by anshumanv** [comment]
Please refrain from sending a PR from master branch of your fork. Please follow these steps -
* First make sure you are in master branch of your fork.
* Pull changes from the upstream to your fork.
* Switch to a different branch.
* Make changes you wish to make.
* Commit changes to newly made branch.
* Push changes to newly made branch.
* Send PR from newly made branch.
This way old commits won't crept in.

**Comment by anshumanv** [comment]
Have invited you to join gitter chatroom, contact there if you have any query.

**Comment by yoksanherlie** [comment]
Should I fork a new one? Because I can't figure out how to revert to the
previous commits and can't get the pull from upstream working.

**Comment by anshumanv** [comment]
Well simplest way is to delete your fork and re-fork to get changes from upstream, you need git shell to get `git pull upstream master` working.

**Comment by yoksanherlie** [comment]
Okay.

Sorry, still a newbie here in the open source world :)

**Comment by anshumanv** [comment]
No problem, everyone was in your shoes at some point. Cheers :smile:

**Pull request closed without merging**
