### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by yoksanherlie**

### CODE REVIEW

**Review by anshumanv — APPROVED** [review]
Looks neat !

**Comment by anshumanv** [comment]
@yoksanherlie are you working on something next ?

**Comment by yoksanherlie** [comment]
I'll try to implement the palette.
But not now. Got other things to do. I'll do it ASAP :smile:

**Comment by anshumanv** [comment]
Sure thing @yoksanherlie , take your time :+1:

**Pull request merged**
